import json
import os
import shutil
import yaml
from dotenv import load_dotenv

load_dotenv()

def automate_new_measure(new_measure_name, source_measure='PSA'):
    """
    Automates the creation of schema and config for a new HEDIS measure.
    Values are cloned from a source measure (default: PSA) and renamed.
    """
    print(f"🚀 Initializing automation for NEW MEASURE: {new_measure_name}")
    
    # 1. Update data_columns_info.json (Schema Definitions)
    json_path = 'data_columns_info.json'
    try:
        with open(json_path, 'r') as f:
            schema = json.load(f)
        
        new_tables = {}
        for table, cols in schema.items():
            if table.startswith(f"{source_measure}_"):
                # Create corresponding table name for new measure
                new_table_name = table.replace(f"{source_measure}_", f"{new_measure_name}_")
                new_tables[new_table_name] = cols
                print(f"  - Generated schema for: {new_table_name}")
        
        # Merge and save
        schema.update(new_tables)
        with open(json_path, 'w') as f:
            json.dump(schema, f, indent=4)
        print("✅ Schema (data_columns_info.json) updated.")
        
    except Exception as e:
        print(f"❌ Failed to update schema: {e}")
        return

    # 2. Generate Full Coverage Blueprint (Blueprint config)
    config_dir = os.getenv('CONFIG_DIR', 'config')
    target_config = os.path.join(config_dir, f'{new_measure_name}.yaml')
    
    blueprint = {
        'measure_name': new_measure_name,
        'description': f'{new_measure_name} HEDIS Measure (Auto-generated Blueprint)',
        'rules': {
            'age_range': [18, 110],
            'age_as_of': 'December 31',
            'anchor_date_type': 'calendar_end',
            'continuous_enrollment': {
                'period_months': 12,
                'allowable_gap_days': 45,
                'no_gap_on_last_day': True
            },
            'initial_population': [
                {
                    'event': 'Standard Visit',
                    'value_set_names': ['Outpatient'],
                    'table': 'visit'
                }
            ],
            'exclusions': [
                {'name': 'Hospice', 'value_set_names': ['Hospice Encounter', 'Hospice Intervention']},
                {'name': 'Death', 'criteria': 'Deceased date within measurement year'}
            ],
            'clinical_events': {
                'numerator_components': [
                    {'name': f'{new_measure_name} Lab Event', 'value_set_names': [f'{new_measure_name} Lab'], 'table': 'lab'},
                    {'name': f'{new_measure_name} Clinical Event', 'value_set_names': [f'{new_measure_name} EMR'], 'table': 'emr'},
                    {'name': f'{new_measure_name} Pharmacy Event', 'value_set_names': [f'{new_measure_name} Rx'], 'table': 'rx'}
                ]
            }
        }
    }
    
    try:
        # If config exists, we don't overwrite it, but print a reminder
        if os.path.exists(target_config):
            print(f"ℹ️  Config file {target_config} already exists. To refresh it, delete it and re-run.")
        else:
            with open(target_config, 'w') as f:
                yaml.dump(blueprint, f, sort_keys=False, default_flow_style=False)
            print(f"✅ Full Coverage Blueprint drafted at {target_config}")
            print("   👉 This config ensures Lab, EMR, and RX tables are generated by default.")
            
    except Exception as e:
        print(f"❌ Failed to create config: {e}")

    print(f"\n✨ Automation Complete! You can now run main.py for {new_measure_name}.")
    print(f"   (Don't forget to add '{new_measure_name}' to the list in main.py)")

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        automate_new_measure(sys.argv[1])
    else:
        print("Usage: python src/measure_automator.py <MEASURE_NAME>")
